name: List trending Go repositories
## Add manual trigger and cron job to run every day at 6 AM UTC
on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  go_list_trending_repos:
    runs-on: ubuntu-latest
    name: A job to list the trending golang repositories on GitHub
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Generate report
        id: complete
        uses: sarvsav/go-list-trending-repos@main
        with:
            since: all
      - name: Save results
        id: json_results
        run: |
          mkdir -p output
          echo '${{ steps.complete.outputs.json_data }}' > output/data.json
      - name: Verify the generated file
        run: |
          cat output/data.json
      - name: Configure Git for commiting the changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - name: Commit and push the changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add output/data.json
          git commit -m "chore: update the list of trending Go repositories"
          git push origin main
